# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 00:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField()),
                ('name', models.CharField(max_length=250)),
                ('path', models.CharField(max_length=250)),
                ('computed_ram', models.IntegerField()),
                ('computed_vcpu', models.IntegerField()),
                ('computed_capacity', models.IntegerField()),
                ('user_ram', models.IntegerField()),
                ('user_vcpu', models.IntegerField()),
                ('ssd_ratio', models.FloatField(default=0.2)),
            ],
        ),
        migrations.CreateModel(
            name='Vm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('cpu', models.IntegerField()),
                ('ram', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('no_disks', models.IntegerField()),
            ],
        ),
    ]
