# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 02:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20171024_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
