# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20171024_0241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='computed_capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='file',
            name='computed_ram',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='file',
            name='computed_vcpu',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='file',
            name='user_ram',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='file',
            name='user_vcpu',
            field=models.IntegerField(default=0),
        ),
    ]
