# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 04:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_auto_20171024_0246'),
    ]

    operations = [
        migrations.AddField(
            model_name='vm',
            name='file',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='portal.File'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vm',
            name='power_state',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='vm',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vm',
            name='cpu',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vm',
            name='no_disks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vm',
            name='ram',
            field=models.IntegerField(default=0),
        ),
    ]
