# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_auto_20171024_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='user_capacity',
            field=models.IntegerField(default=0),
        ),
    ]
